name = "Tag Discount Function App"
client_id = "4dc11c9394b4df7ae6fa0cf17bac1345"
application_url = "https://custom-shopify-app.onrender.com"
embedded = true

[auth]
redirect_urls = ["https://custom-shopify-app.onrender.com/auth/callback"]
access_scopes = "read_products,write_products,read_customers,write_discounts,read_shipping,write_shipping"

[webhooks]
api_version = "2024-04"

[[extensions]]
type = "discount_function"
name = "Tag Discount Function"
handle = "tag-discount-function"
path = "extensions/tag-discount-function"
